
; (begin_fill)
(define (piece order size)
  (cond ((= 0 order) (fd size))
        (else (begin (define s_size (+ 1 (* 0.8715574274765817 (/ size 2))))
          (color "#285078")
          (begin_fill)
          (piece (- order 1) s_size)
          (lt 85)
          (piece (- order 1) s_size)
          (lt 190)
          (piece (- order 1) s_size)
          (lt 85)
          (piece (- order 1) s_size)
          (lt 0)
          (end_fill)
          ))
    )
  )
; (color "#285078")
(define (square_piece order size)
  (piece order size)
  (lt 90)
  (piece order size)
  (lt 90)
  (piece order size)
  (lt 90)
  (piece order size)
  (lt 90)
  )

(speed 0)
(square_piece 3 200)
; (end_fill)